---
title: "Analysis of Landfall of Hurricane Gustav 2008"
author: "Mi Zhang, Qiannan Shen, Peng Liu, Yujia Wang"
date: "11/21/2021"
output: 
  pdf_document: 
    latex_engine: lualatex
header-includes: 
  - \usepackage{setspace}\renewcommand{\baselinestretch}{1.5}
  - \setlength{\parindent}{2em}
  - \usepackage{float}
---

```{r setup, include=FALSE}

# source("gustav.R")
# source("buoy data/timeseries.R")
# source("variogram.R")
# source("buoy_map.R")
# source("data table.R")
# source("variogram——test.R")

```

```{r echo = FALSE, message=FALSE}

library(dplyr)
library(hurricaneexposuredata)
library(hurricaneexposure)
library(kableExtra)

gustav_rain <- filter(rain, rain$storm_id == "Gustav-2008" & rain$lag == 0)

#counties' latitude and longitude
data(county_centers)

#wind
data(storm_winds)

#filter needed data for Gustav
gustav_winds <- filter(storm_winds, storm_id=="Gustav-2008")

#combine three datasets into one dataset, including all needed variables
gustav_county <- county_centers %>% inner_join(gustav_rain,by="fips")
gustav <- gustav_county %>% inner_join(gustav_winds, by=c("fips", "storm_id", "usa_atcf_id"))

table_variogram <- gustav %>%
  rename(county = "county_name") %>%
  rename(state = "state_name")

kable(gustav[c(913, 910, 915, 953, 900, 938, 922), c(1:3, 5, 6, 9:13)], caption = "Data frame for variogram in daily precipitation", booktabs = T) %>%
  kable_styling(latex_option = "striped")

```