---
title: "Map of hurricane"
author: "Mi Zhang, Peng Liu, Qiannan Shen, Yujia Wang"
date: "11/17/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# variogram
library(sp)
library(gstat)
library(tmap)
# install.packages("automap")
library(automap)
# time seires
library(geoR)
library(tidyr)
library(ggplot2)
```

## Data cleaning and wrangling

```{r}
source("gustav.R")

gustav_rain <- filter(rain, rain$storm_id == "Gustav-2008" & rain$lag ==0)

data(storm_winds)
gustav_winds <- filter(storm_winds, storm_id=="Gustav-2008")

data(county_centers)
gustav_county<- county_centers %>% inner_join(gustav_rain,by="fips")
gustav <- gustav_county %>% inner_join(gustav_winds, by=c("fips", "storm_id", "usa_atcf_id"))
```

## Variogram

```{r}
gustav_var <- gustav[, c(1, 5, 6, 9:13)]

# variogram: precip_max
gustav_var$y = as.numeric(gustav_var$latitude)
gustav_var$x = as.numeric(gustav_var$longitude)
coordinates(gustav_var) = ~x+y
spherical_variogram <- function (n, ps, r) function (h) {
  h <- h / r
  n + ps * ifelse(h < 1, 1.5 * h - .5 * h ^ 3, 1)
}
v_f <- spherical_variogram(v_fit$psill[1], v_fit$psill[2], v_fit$range[2])
v <- variogram(precip_max ~ 1, gustav_var)
v_fit <- fit.variogram(v, vgm("Sph"))

h <- seq(0, 100, length = 1000)
plot(v$dist, v$gamma,
     xlab = "distance", ylab = "semivariogram")
lines(h, v_f(h))
abline(v = v_fit$range[2], col = "gray")

#v_mod_OK <- automap::autofitVariogram(precip_max ~ x+y, gustav_var)$var_model
#plot(automap::autofitVariogram(vmax_gust ~ x+y, gustav_var))
```

```{r}
# variogram: vmax_gust
gustav_var$y = as.numeric(gustav_var$latitude)
gustav_var$x = as.numeric(gustav_var$longitude)
coordinates(gustav_var) = ~x+y
gaussian_variogram <- function (n, ps, r)
  function (h) n + ps * (1 - exp(-(h / r) ^ 2))
v_f <- gaussian_variogram(v_fit$psill[1], v_fit$psill[2], v_fit$range[2])
v <- variogram(vmax_gust ~ 1, gustav_var)
v_fit <- fit.variogram(v, vgm("Gau"))

h <- seq(0, 50, length = 1000)
plot(v$dist, v$gamma,
     xlab = "distance", ylab = "semivariogram")
lines(h, v_f(h))
abline(v = v_fit$range[2], col = "gray")

#v_mod_OK <- automap::autofitVariogram(vmax_gust ~ x+y, gustav_var)$var_model
#plot(automap::autofitVariogram(vmax_gust ~ x+y, gustav_var))
```

## Time seires

```{r}
# read data
data42003 <- read.csv("buoy data/42003.csv")
data42007 <- read.csv("buoy data/42007.csv")
data42039 <- read.csv("buoy data/42039.csv")
data42040 <- read.csv("buoy data/42040.csv")
data42059 <- read.csv("buoy data/42059.csv")

# data clean
hi <- function(x){
  x <- x[-1,]
  x$hh <- formatC(as.numeric(x$hh), flag = 0, width = 2)
  x$DD <- formatC(as.numeric(x$DD), flag = 0, width = 2)
  x$MM <- formatC(as.numeric(x$MM), flag = 0, width = 2)
  x <- unite(x, X.YY, MM, DD, col = "Datetime", sep = "-")
  x <- unite(x, hh, mm, col = "Time", sep = ":")
  x$date_time <- paste(x$Datetime, x$Time, sep = " ")
  x$date_time <- as.POSIXct(x$date_time,
                                     format="%Y-%m-%d %H:%M") #format time
  return(x)
}

data42003_clean <- hi(data42003)
data42003_clean <- data42003_clean[c(5500:5658),]#missing 9-11

data42007_clean <- hi(data42007)#8/29 begins
data42007_clean <- data42007_clean[c(4286:4413),]

data42039_clean <- hi(data42039)
data42039_clean <- data42039_clean[c(5675:5913),]

data42040_clean <- hi(data42040)
data42040_clean <- data42040_clean[c(3453:3691),]

data42059_clean <- hi(data42059)
data42059_clean <- data42059_clean[c(5684:5921),]

# plot
colors <- c("42003" = "gray", "42007" = "tomato", "42039" = "pink", "42040" = "skyblue", "42059" = "orange")

ggplot()+
  geom_line(data = data42003_clean, aes(x=date_time, y=as.numeric(WDIR), color = "42003"))+
  geom_line(data = data42007_clean, aes(x=date_time, y=as.numeric(WDIR), color = "42007")) +
  geom_line(data = data42039_clean, aes(x=date_time, y=as.numeric(WDIR), color = "42039")) +
  geom_line(data = data42040_clean, aes(x=date_time, y=as.numeric(WDIR), color = "42040")) +
  geom_line(data = data42059_clean, aes(x=date_time, y=as.numeric(WDIR), color = "42059")) +
  labs(y = "WDIR", x = "time", color = "Legend")+
  scale_color_manual(values = colors)

ggplot()+
  geom_line(data = data42003_clean, aes(x=date_time, y=as.numeric(GST), color = "42003"))+
  geom_line(data = data42007_clean, aes(x=date_time, y=as.numeric(GST), color = "42007")) +
  geom_line(data = data42039_clean, aes(x=date_time, y=as.numeric(GST), color = "42039")) +
  geom_line(data = data42040_clean, aes(x=date_time, y=as.numeric(GST), color = "42040")) +
  geom_line(data = data42059_clean, aes(x=date_time, y=as.numeric(GST), color = "42059")) +
  labs(y = "GST", x = "time", color = "Legend")+
  scale_color_manual(values = colors)
```




